version: '3.5'
services:
    angular-service:
      container_name: angularcontainer 
      build: ./
      volumes:
        - './:/usr/src/app'
      ports: 
        - '80:80'
      command: sh -c "./filecount.sh && npm run start:docker"